const letterNames = {
    "א": "alef",
    "ב": "bet",
    "בּ": "bet_dagesh",
    "ג": "gimel",
    "ד": "dalet",
    "ה": "he",
    "ו": "vav",
    "ז": "zayin",
    "ח": "chet",
    "ט": "tet",
    "י": "yud",
    "כ": "kaf",
    "כּ": "kaf_dagesh",
    "ל": "lamed",
    "מ": "mem",
    "נ": "nun",
    "ס": "samech",
    "ע": "ayin",
    "פ": "pe",
    "פּ": "pe_dagesh",
    "צ": "tsadi",
    "ק": "kuf",
    "ר": "resh",
    "שׂ": "shin_sin",
    "שׁ": "shin_shin",
    "ת": "tav",
    "תּ": "tav_dagesh",
  };
  
  const nikudNames = {
    "ָ": "kamatz",
    "ַ": "patah",
    "ֵ": "tsere",
    "ֶ": "segol",
    "ִ": "hiriq",
    "ְ": "sheva",
    "ּ": "dagesh",
  };
  
  const InputNikud = {
    "א": { 
      "ָ": "MultipleFiles/Kamatz/Boo.m4a", 
      "ַ": "MultipleFiles/Pasach or Patach/Aaa.m4a", 
      "ֵ": "MultipleFiles/Tzeirey/Aye.m4a", 
      "ֶ": "MultipleFiles/Segol/Aye.m4a",
      "ִ": "MultipleFiles/Chirik/Eee.m4a", 
      "ְ": "MultipleFiles/Shvu-(also default sound)/א-A.m4a", 
      "ּ": "MultipleFiles/Choilem or Cholam/Oiy.m4a", 
    },
    "ב": { 
      "ָ": "MultipleFiles/Kamatz/Choo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Baa.m4a", 
      "ֵ": "MultipleFiles/Tzeirey/Bye.m4a", 
      "ֶ": "MultipleFiles/Segol/Baye.m4a", 
      "ִ": "MultipleFiles/Chirik/Bee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ב-V.m4a", 
      "ּ": "MultipleFiles/Choilem or Cholam/Boiy.m4a", 
    },
    "בּ": { 
      "ָ": "MultipleFiles/Kamatz/Choo2.m4a", 
      "ַ": "MultipleFiles/Pasach or Patach/Vaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Vye.m4a",
      "ֶ": "MultipleFiles/Segol/Vaye.m4a", 
      "ִ": "MultipleFiles/Chirik/Vee.m4a", 
      "ְ": "MultipleFiles/Shvu-(also default sound)/בּ-B.m4a", 
      "ּ": "MultipleFiles/Choilem or Cholam/Voiy.m4a", 
    },
    "ג": { 
      "ָ": "MultipleFiles/Kamatz/Doo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Gaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Gye.m4a", 
      "ֶ": "MultipleFiles/Segol/Gaye.m4a", 
      "ִ": "MultipleFiles/Chirik/Gee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ג-G.m4a", 
      "ּ": "MultipleFiles/Choilem or Cholam/Goiy.m4a",
    },
   
    "ד": {
      "ָ": "MultipleFiles/Kamatz/Foo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Daa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Dye.m4a",
      "ֶ": "MultipleFiles/Segol/Daye.m4a",
      "ִ": "MultipleFiles/Chirik/Dee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ד-D.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Doiy.m4a",
    },
    "ה": {
      "ָ": "MultipleFiles/Kamatz/Goo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Haa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Hye.m4a",
      "ֶ": "MultipleFiles/Segol/Haye.m4a",
      "ִ": "MultipleFiles/Chirik/Hee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ה-H.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Hoiy.m4a",
    },
    "ו": {
      "ָ": "MultipleFiles/Kamatz/Hoo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Vaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Vye2.m4a",
      "ֶ": "MultipleFiles/Segol/Vaye2.m4a",
      "ִ": "MultipleFiles/Chirik/Vee2.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ו-V.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Voiy2.m4a",
    },
    "ז": {
      "ָ": "MultipleFiles/Kamatz/Koo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Zaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Zye.m4a",
      "ֶ": "MultipleFiles/Segol/Zaye.m4a",
      "ִ": "MultipleFiles/Chirik/Zee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ז-Z.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Zoiy.m4a",
    },
    "ח": {
      "ָ": "MultipleFiles/Kamatz/Koo2.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Chaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Chye.m4a",
      "ֶ": "MultipleFiles/Segol/Chaye.m4a",
      "ִ": "MultipleFiles/Chirik/chee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ח-CH.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Choiy.m4a",
    },
    "ט": {
      "ָ": "MultipleFiles/Kamatz/Loo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Taa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Tye.m4a",
      "ֶ": "MultipleFiles/Segol/Taye.m4a",
      "ִ": "MultipleFiles/Chirik/Tee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ט-T.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Toiy.m4a",
    },
    "י": {
      "ָ": "MultipleFiles/Kamatz/Moo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Yaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Yye.m4a",
      "ֶ": "MultipleFiles/Segol/Yaye.m4a",
      "ִ": "MultipleFiles/Chirik/Yee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/י-Y.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Yoiy.m4a",
    },
    "כ": {
      "ָ": "MultipleFiles/Kamatz/Noo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Kaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Kye.m4a",
      "ֶ": "MultipleFiles/Segol/Kaye.m4a",
      "ִ": "MultipleFiles/Chirik/Kee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/כ-CH.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Koiy.m4a",
    },
    "כּ": {
      "ָ": "MultipleFiles/Kamatz/Ooo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Chaa2.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Chye2.m4a",
      "ֶ": "MultipleFiles/Segol/Chaye2.m4a",
      "ִ": "MultipleFiles/Chirik/Chee(1).m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/כּ-K.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Choiy.m4a",
    },
    "ל": {
      "ָ": "MultipleFiles/Kamatz/Ooo2.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Laa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Lye.m4a",
      "ֶ": "MultipleFiles/Segol/Laye.m4a",
      "ִ": "MultipleFiles/Chirik/Lee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ל-L.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Loiy.m4a",
    },
    "מ": {
      "ָ": "MultipleFiles/Kamatz/Poo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Maa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Mye.m4a",
      "ֶ": "MultipleFiles/Segol/Maye.m4a",
      "ִ": "MultipleFiles/Chirik/Mee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/מ-M.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Moiy.m4a",
    },
    "נ": {
      "ָ": "MultipleFiles/Kamatz/Roo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Naa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Nye.m4a",
      "ֶ": "MultipleFiles/Segol/Naye.m4a",
      "ִ": "MultipleFiles/Chirik/Nee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/נ-N.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Noiy.m4a",
    },
    "ס": {
      "ָ": "MultipleFiles/Kamatz/Shoo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Saa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Sye.m4a",
      "ֶ": "MultipleFiles/Segol/Saye.m4a",
      "ִ": "MultipleFiles/Chirik/See.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ס-S.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Soiy.m4a",
    },
    "ע": {
      "ָ": "MultipleFiles/Kamatz/Soo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Aaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Aye.m4a",
      "ֶ": "MultipleFiles/Segol/Aye2.m4a",
      "ִ": "MultipleFiles/Chirik/Eee2.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ע-A.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Oiy2.m4a",
    },
    "פ": {
      "ָ": "MultipleFiles/Kamatz/Soo2.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Paa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Pye.m4a",
      "ֶ": "MultipleFiles/Segol/Paye.m4a",
      "ִ": "MultipleFiles/Chirik/Pee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/פ-F.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Poiy.m4a",
    },
    "פּ": {
      "ָ": "MultipleFiles/Kamatz/Soo3.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Faa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Fye.m4a",
      "ֶ": "MultipleFiles/Segol/Faye.m4a",
      "ִ": "MultipleFiles/Chirik/Fee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/פּ-P.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Foiy.m4a",
    },
    "צ": {
      "ָ": "MultipleFiles/Kamatz/Too.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Tzaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Tzye.m4a",
      "ֶ": "MultipleFiles/Segol/Tzaye.m4a",
      "ִ": "MultipleFiles/Chirik/Tzee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/צ-TZ.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Tzoiy.m4a",
    },
    "ק": {
      "ָ": "MultipleFiles/Kamatz/Too2.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Kaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Kye2.m4a",
      "ֶ": "MultipleFiles/Segol/Kaye.m4a",
      "ִ": "MultipleFiles/Chirik/Kee2.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ק-K.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Koiy2.m4a",
    },
    "ר": {
      "ָ": "MultipleFiles/Kamatz/Tzoo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Raa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Rye.m4a",
      "ֶ": "MultipleFiles/Segol/Raye.m4a",
      "ִ": "MultipleFiles/Chirik/Ree.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ר-R.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Roiy.m4a",
    },
    "שׂ": {
      "ָ": "MultipleFiles/Kamatz/Voo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Shaa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Shye.m4a",
      "ֶ": "MultipleFiles/Segol/Shaye.m4a",
      "ִ": "MultipleFiles/Chirik/Shee.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/שׁ-SH.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Soiy2.m4a",
    },
    "שׁ": {
      "ָ": "MultipleFiles/Kamatz/Voo2.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Saa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Sye2.m4a",
      "ֶ": "MultipleFiles/Segol/Saye2.m4a",
      "ִ": "MultipleFiles/Chirik/See2.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/שׁ-S.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Soiy3.m4a",
    },
    "ת": {
      "ָ": "MultipleFiles/Kamatz/Yoo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Taa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Tye2.m4a",
      "ֶ": "MultipleFiles/Segol/Taye2.m4a",
      "ִ": "MultipleFiles/Chirik/Tee2.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/ת-S.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Toiy2.m4a",
    },
    "תּ": {
      "ָ": "MultipleFiles/Kamatz/Zoo.m4a",
      "ַ": "MultipleFiles/Pasach or Patach/Saa.m4a",
      "ֵ": "MultipleFiles/Tzeirey/Sye3.m4a",
      "ֶ": "MultipleFiles/Segol/Saye3.m4a",
      "ִ": "MultipleFiles/Chirik/See3.m4a",
      "ְ": "MultipleFiles/Shvu-(also default sound)/תּ-T.m4a",
      "ּ": "MultipleFiles/Choilem or Cholam/Shoiy.m4a",
    },
  };
  
  // Attach to global window object for non-module access
  window.letterNames = letterNames;
  window.nikudNames = nikudNames;
  window.InputNikud = InputNikud;